name:                zap
version:             0.1.0.0
github:              "githubuser/zap"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/zap#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.11 && < 3
- parsec >= 3.1 && < 4
- megaparsec >= 9.6 && < 10
- mtl >= 2.3 && < 3
- text >= 2.1 && < 3
- filepath >= 1.4 && < 2
- process >= 1.6 && < 2
- directory >= 1.3 && < 2
- containers >= 0.6 && < 1
- parser-combinators >= 1.3 && < 2
- time >= 1.12 && < 2
- transformers >= 0.6 && < 1
- temporary >= 1.3 && < 2
- array >= 0.5 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-name-shadowing
- -fno-warn-incomplete-uni-patterns
- -fno-warn-type-defaults
- -fno-warn-overlapping-patterns
- -fno-warn-x-partial

library:
  source-dirs: src

executables:
  zap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zap

tests:
  zap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zap
